//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camplots.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buoyTypes
    {
        public string buoyTypeName { get; set; }
        public string buoyTypeDescr { get; set; }
        public byte[] buoyTypeImage { get; set; }
    }
}
