//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camplots.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParksAndLandsEntities : DbContext
    {
        public ParksAndLandsEntities()
            : base("name=ParksAndLandsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<inspections> inspections { get; set; }
        public virtual DbSet<latLon> latLon { get; set; }
        public virtual DbSet<mapinfo_prinx> mapinfo_prinx { get; set; }
        public virtual DbSet<owners> owners { get; set; }
        public virtual DbSet<plumbingInspectors> plumbingInspectors { get; set; }
        public virtual DbSet<rents> rents { get; set; }
        public virtual DbSet<sites> sites { get; set; }
        public virtual DbSet<structures> structures { get; set; }
        public virtual DbSet<towns> towns { get; set; }
        public virtual DbSet<valuations> valuations { get; set; }
        public virtual DbSet<z_photo_test> z_photo_test { get; set; }
        public virtual DbSet<buoyTypes> buoyTypes { get; set; }
    }
}
