//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camplots.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class owners
    {
        public int Camplot_ID { get; set; }
        public string VEND_CUST_CD { get; set; }
        public string FSNAME { get; set; }
        public string LNAME { get; set; }
        public string CONAME { get; set; }
        public string AddName { get; set; }
        public string ADDRESS { get; set; }
        public string TOWN { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string HOME_PHONE { get; set; }
        public string CELL_PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> TRANSFER_DATE { get; set; }
        public string FORMER_OWNER_NOTES { get; set; }
        public Nullable<bool> Seboeis_Dam_Mailing { get; set; }
    }
}
