//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camplots.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rents
    {
        public int Camplot_ID { get; set; }
        public short FEEYear { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<bool> Partial_Pmt { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<decimal> AmmountPaid { get; set; }
    }
}
