//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camplots.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sites
    {
        public int CAMPLOT_ID { get; set; }
        public string MIDAS { get; set; }
        public string LOTNOS { get; set; }
        public string LOCATION { get; set; }
        public string WATERBODY { get; set; }
        public string CTY { get; set; }
        public string ROAD_NAME { get; set; }
        public string ACCESS { get; set; }
        public Nullable<double> FRONTAGE { get; set; }
        public Nullable<double> DEPTH { get; set; }
        public Nullable<double> ACREAGE { get; set; }
        public string CODE { get; set; }
        public bool DRIVEWAY { get; set; }
        public bool PARKING { get; set; }
        public Nullable<int> PARKING_ { get; set; }
        public string OWNRS_ASSN { get; set; }
        public string VEGETATION { get; set; }
        public string SOIL { get; set; }
        public Nullable<int> SLOPE_FRONT { get; set; }
        public Nullable<int> SLOPE_BACK { get; set; }
        public string ENLARGE { get; set; }
        public string LOT_LINES { get; set; }
        public string NOTES { get; set; }
        public bool Parks { get; set; }
        public string Comercial { get; set; }
        public bool RevSharing { get; set; }
        public bool Archive { get; set; }
        public string ArchiveDate { get; set; }
        public Nullable<System.DateTime> LeaseEndDate { get; set; }
        public string CommercialSpecialNotes { get; set; }
        public string Map { get; set; }
        public string Plan { get; set; }
        public string Lot { get; set; }
        public string CustomerNumber { get; set; }
        public string WasteWaterSystemStatus { get; set; }
        public bool Cancelled { get; set; }
        public Nullable<System.DateTime> INSPECTN_DATE { get; set; }
        public string INSPECTORS { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public string VEND_CUST_CD { get; set; }
        public string FSNAME { get; set; }
        public string LNAME { get; set; }
        public string CONAME { get; set; }
        public string AddName { get; set; }
        public string ADDRESS { get; set; }
        public string TOWN { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string HOME_PHONE { get; set; }
        public string CELL_PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> TRANSFER_DATE { get; set; }
        public string FORMER_OWNER_NOTES { get; set; }
        public bool Seboeis_Dam_Mailing { get; set; }
    }
}
