//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camplots.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class structures
    {
        public int id { get; set; }
        public Nullable<int> Camplot_ID { get; set; }
        public string STRUCTURE_DESC { get; set; }
        public string CONDITION { get; set; }
        public string ROOF_TYPE { get; set; }
        public string SIDING { get; set; }
        public string FOUNDATION { get; set; }
        public string FOUND_CONDITION { get; set; }
        public Nullable<double> WATER_DISTANCE { get; set; }
        public string TOILET_TYPE { get; set; }
        public string LOCATION { get; set; }
        public string T_WTR_DISTANCE { get; set; }
        public string T_CONDITION { get; set; }
        public string GREY_WATER { get; set; }
        public string VENT_PIPES { get; set; }
        public string SEPTIC_FIELD { get; set; }
        public Nullable<double> G_WTR_DISTANCE { get; set; }
        public string G_CONDITION { get; set; }
        public Nullable<bool> G_COMPLIANCE { get; set; }
        public string GARBAGE_DISPOSAL { get; set; }
        public string WATER_SUPPLY { get; set; }
        public string PIPED_WATER { get; set; }
        public string HEATING { get; set; }
        public string STOVE_PIPES { get; set; }
        public string SCREENED { get; set; }
        public string COOKING { get; set; }
        public string LIGHTING { get; set; }
        public string AC_ELECTRIC { get; set; }
        public string TELEPHONE { get; set; }
        public string AUX_STRUCT { get; set; }
        public string AUX_DESC { get; set; }
        public string DOCK { get; set; }
        public string DOCK_DESC { get; set; }
        public string COMMENTS { get; set; }
        public string PHOTO { get; set; }
        public Nullable<bool> ShoreLand { get; set; }
    }
}
