//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camplots.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class towns
    {
        public string Midas { get; set; }
        public string Town_name2 { get; set; }
        public string LANDSREGION { get; set; }
        public Nullable<bool> SpecialBilling { get; set; }
        public Nullable<int> SpecialAmount { get; set; }
        public Nullable<double> RevSharing_Stumpage { get; set; }
        public Nullable<double> RevShare_Camplot { get; set; }
        public string region { get; set; }
        public Nullable<int> plumbingInspectorId { get; set; }
    }
}
